openapi: 1
info:
  version: '1'
  title: Demo API
  description: End-of-internship project API
servers:
  - description: API Server
    url: 'https://__EXTERNAL_API_DOMAIN__/'
tags:
  - name: Sum-UP Calculator
paths:
  /api/v1/calculation:
    post:
      operationId: calculateUnspecified
      summary: Calculate for generated user ID
      description: Return a subset sum of provided integers closest to a requested total
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/request'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/response'
  /api/v1/calculation/{user}:
    parameters:
      - $ref: '#/components/schemas/user'
      - name: user
        in: path
        description: Username
        required: false
        schema:
          type: string
    post:
      operationId: calculateSpecified
      summary: Calculate for provided user ID
      description: Return a subset sum of provided integers closest to a requested total
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/request'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/demodb'
  /api/v1/history:
    get:
      operationId: showCalcualtionHistory
      summary: Show Calculation History
      description: Get previous calculations
      tags:
        - Calculation History
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/advanced_activity_analytics_request'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/history'
components:
  schemas:
    request:
      type: object
      required:
        - userId
        - total
        - valuesX
      properties:
        userId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440000
        total:
          type: integer
          format: int64
          example: 1000
        valuesX:
          type: array
            items:
              type: integer
              format: int64
              example: [1, 3, 4]
    response:
      type: object
      required:
        - result
      properties:
        result:
          type: array
            items:
              type: integer
              format: int64
              example: [ 1, 3, 4 ]
    history:
      type: object
      required:
        - userId
        - total
        - valuesX
        - result
      properties:
        userId:
          type: string
          format: uuid
          example: 123e4567-e89b-12d3-a456-426655440000
        total:
          type: integer
          format: int64
          example: 1000
        valuesX:
          type: array
            items:
              type: integer
              format: int64
              example: [ 1, 3, 4 ]
        result:
          type: array
            items:
              type: integer
              format: int64
              example: [ 1, 3, 4 ]
    user:
      type: string